#!/bin/bash

ITEMS=(
    CO2_WLULUCF=http://unfccc.int/ghg_data/ghg_data_unfccc/time_series_annex_i/items/3844.php
    CH4_WLULUCF=http://unfccc.int/ghg_data/ghg_data_unfccc/time_series_annex_i/items/3846.php
    N2O_WLULUCF=http://unfccc.int/ghg_data/ghg_data_unfccc/time_series_annex_i/items/3848.php
    SF6_WLULUCF=http://unfccc.int/ghg_data/ghg_data_unfccc/time_series_annex_i/items/4131.php
)

for ITEM in "${ITEMS[@]}"; do
    FNAME="${ITEM%%=*}"
    URL="${ITEM#*=}"
    wget -q -O- "${URL}" | \
        tidy -asxhtml -indent -numeric -quiet 2> /dev/null | \
        xmlstarlet \
            sel -N x="http://www.w3.org/1999/xhtml" \
                -t -m "//x:div[@class='contpart']/x:table/x:tbody" \
                    -m "x:tr" \
                        -m "x:td[not(position()=10) and not(position()=2)]" \
                           -c "translate(normalize-space(.), ',', '')" \
                           -i 'not(position()=last())' -o ':' -b \
                    -b -n | \
        sed '1,2s/^/# /' > "${FNAME}.CSV" &
done
wait
