#!/bin/bash

join <(
    for G in SF6 CO2 N2O CH4; do
        awk -v GAS="$G" '
        BEGIN { FS=OFS=":" }
        NR==1 { next }
        NR==2 { for(i = 2; i <= NF; ++i) Y[i]=$i }
        NR>2 {
            for(i = 2; i <= NF; ++i) {
                if ($i) print $1, Y[i], GAS, sprintf("%8.2f",$i);
            }
        }
        ' ${G}_WLULUCF.CSV
    done | sort -t: -k1
) <(sort -t: -k2 ISO3166.CSV ) -t: -1 1 -2 2 -e XXX -o 2.1,1.2,1.3,1.4 \
        | sort \
        | tee >(grep "^..:1990" > GHG_EMISSIONS_1990.CSV) \
              >(grep "^..:1995" > GHG_EMISSIONS_1995.CSV) \
              >(grep "^..:2000" > GHG_EMISSIONS_2000.CSV) \
              >(grep "^..:2005" > GHG_EMISSIONS_2005.CSV) \
              >(grep "^..:2010" > GHG_EMISSIONS_2010.CSV) \
              >(grep "^..:2011" > GHG_EMISSIONS_2011.CSV) \
              >(grep "^..:2012" > GHG_EMISSIONS_2012.CSV) \
    > GHG_EMISSIONS.CSV
