#!/bin/bash

join <(
    for G in CO2 N2O CH4; do
        awk -v GAS="$G" '
        BEGIN { FS=OFS=":" }
        NR==1 { next }
        NR==2 { for(i = 2; i <= NF; ++i) Y[i]=$i }
        NR>2 {
            for(i = 2; i <= NF; ++i) {
                print $1, Y[i], GAS, $i;
            }
        }
        ' ${G}_WLULUCF.CSV
    done | sort -t: -k1
) <(sort -t: -k2 iso3166.csv ) -t: -1 1 -2 2 -e XXX -o 2.1,1.2,1.3,1.4 > GHG_EMISSIONS.CSV
