#!/bin/bash

join <(
    for G in SF6 CO2 N2O CH4; do
        awk -v GAS="$G" '
        BEGIN { FS=OFS=":" }
        NR==1 { next }
        NR==2 { for(i = 2; i <= NF; ++i) Y[i]=$i }
        NR>2 {
            for(i = 2; i <= NF; ++i) {
                if ($i) print $1, Y[i], GAS, sprintf("%9.2f",$i);
            }
        }
        ' ${G}_WLULUCF.CSV
    done | sort -t: -k1
) <(sed -E 's/ +:/:/g' ISO3166.CSV | sort -t: -k1,1 ) -t: -1 1 -2 1 -e XXX -o 2.2,1.2,1.3,1.4 \
    | sort \
    > GHG_EMISSIONS.CSV
